### PR TITLE
Make test script run out of the box

### PR DESCRIPTION
**Pull request by alexanderwallin**
As per the discussion in https://github.com/audiojs/audio-context/issues/12, this PR defines the tools and scripts needed to run its tests out of the box.

### CODE REVIEW

**Comment by juliangruber** [comment]
travis needs some extra configuration for this: https://github.com/juliangruber/browser-run#headless-testing

**Comment by alexanderwallin** [comment]
Tests are not passing yet 😕

**Comment by dfcreative** [comment]
@alexanderwallin I've fixed the test, thanks for the PR!

**Comment by alexanderwallin** [comment]
Ah, swell.

**Pull request merged**
